### ISSUE TITLE
Installer does not prompt to edit sysctl

### ISSUE THREAD

**Issue by sdressler** [swarm64/s64da-installer#5]
## Summary

The installer does not ask the user to edit the sysctl configuration.

## Reproduction

1. Clone the installer
2. Run an installation of any type, e.g. `--type cpu`

## Observation

The user will be asked to edit the PostgreSQL configuration file but not to review the sysctl configuration.

## Expectation

The user should be asked to review the sysctl configuration.

**Comment by jukoson** [comment]
Displaying / Editing sysctl is not desired at the moment. I will add a message that displays the location of the sysctl file so that the user can review if required.
